### ISSUE TITLE
💡 cloudflared Cloudflare Tunnel HTTP Traffic Metrics

### ISSUE THREAD

**Issue by STRRL** [cloudflare/cloudflared#1001]
**Describe the feature you'd like**

Provide more Prometheus metrics data about the traffic.

**Describe alternatives you've considered**

I run `cloudflared` inside of kubernetes, so I would monitoring the network traffic about pod.

But there is NO way to get detailed metrics like "how much traffic used for ingress and egress with domain `service1.example.com` ".

**Additional context**

Now cloudflared already provides some metrics in proxy/metrics.go, like counter by http response code.

I want more metrics like the counter of proxied traffic data in bytes, for both ingress and egress.

I found that I could append more instrument behavior around `proxy/metrics.go` to accomplish this goal.

Also the well-design of metrics(name, tags) should be considered.

What do you think about it?

**Comment by obezuk** [comment]
Hi there,

The cloudflared metrics service is designed to help administrators monitor the health / load of their cloudflared instances, not provide granular analytics.

We need to be really thoughtful about adding labels to metrics too. Labels greatly increases cardinality and significantly increase load on Prometheus servers. For customers with many domains this could become unwieldily very quickly.

That being said, one can already pull hostname level metrics from Cloudflare's analytics (as all this traffic flows through Cloudflare), and you could monitor the ingress/egress traffic of your cloudflared pods with cadvisor.

Here is a blog post about how to consume Cloudflare's analytics in Prometheus: https://blog.cloudflare.com/improving-your-monitoring-setup-by-integrating-cloudflares-analytics-data-into-prometheus-and-grafana/

**Comment by STRRL** [comment]
Great! I would take a look!

**Comment by STRRL** [comment]
Hi @obezuk , I took a quick walkthrough about the post, Cloudflare Analytics API and cloudflare-exporter project, and huge thanks to cloudflare that already provided the powerful analytics feature and easy-to-use API.

But I found that for Free Plan user, `httpRequests1mGroups` is not available, so it's not useable for all users.

I might fork cloudflared to adapt the traffic usage analytics in the future, and I am very glad backport to upstream if you think it makes sense one day :D

Thanks!

**Comment by damongabrielle** [comment]
I came across this while looking for searching for exactly this: why host level prometheus metrics were not being emitted from cloudflared. I had a feeling there might be cardinality concerns and I can somewhat understand why. I do use the analytics dashboards in cloudflare to achieve this visibility instead. I also use Istio Gateway Prometheus metrics to see hostnames since that's in the request path as well. Begs the question why is istio more liberal with its metrics cardinality wrt to hostsnames? 
However, there is something to be said for seeing similar data in our own prometheus dashboards from cloudflare...especially right next to Istio. 
What if metrics were emitted on the ingress rule match number? Would that be cardinality conscious middleground? OR what if metrics were explicitly enabled per ingress rule rather than hostname so that we could take cardinality concerns into our own hands?

**Comment by STRRL** [comment]
Hi community! I build a forked version of cloudflared with metrics, and grafana dashboards

https://github.com/strrl/cloudflared/

<img width="2560" height="1830" alt="Image" src="https://github.com/user-attachments/assets/76bc7578-4017-4485-b0a6-cedd277e3d63" />

About cardinality, at 2026, there're some high cardinality solution for metrics (for example clickhouse timeseries table), I think it would not be a huge issue now.

I am going to reopen this PR, and please let me know if cloudflare team would like to accept this improvement, I am happy to contribute PRs. 

Also feel free to close this issue if you do not think it's time to do it, I am OK with forked version : ) Thanks!
