### ISSUE TITLE
🐛 `2024.1.0` is missing `cloudflared-linux-amd64.deb`

### ISSUE THREAD

**Issue by shayonj** [cloudflare/cloudflared#1144]
**Describe the bug**
Looks like the latest release does no longer contain `cloudflared-linux-amd64.deb` - https://github.com/cloudflare/cloudflared/releases/tag/2024.1.0. Is that expected?

**To Reproduce**
Latest release: https://github.com/cloudflare/cloudflared/releases/tag/2024.1.0

**Expected behavior**
 Older releases that have it - https://github.com/cloudflare/cloudflared/releases/tag/2023.10.0

**Comment by simonh-tecex** [comment]
Please escalate, this is not "Priority: Normal"!

During system start we run this Curl in order to retrieve the latest cloudflared and use it:

`curl --max-time 10 -s -L "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH_DPKG}" -o /root/cloudflared`

Where `ARCH_DPKG` is either `amd64` or `arm64`

As of this latest release, this curl is *PASSING* with an HTTP 200, but saves a file that has the text "Not found"!!

Our system then proceeds to use cloudflared to run argo tunnels, and it is a problem trying to set up an argo tunnel with a text file with the words "Not found".

After a brief outtage we have been able to work around this incomplete release for now.

However, it will continue to cause problems in some of our new image build pipelines until resolved.

There is nothing on the official download page about any changes to the binaries available.

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/

(developers dot cloudflare dot com slash cloudflare-one slash connections slash connect-networks slash downloads)

Please do resolve asap!

**Comment by joliveirinha** [comment]
Sorry. There was a bad release. We already removed the release from github.
