### ISSUE TITLE
🐛Version 2024.1.2 not starting on W7

### ISSUE THREAD

**Issue by lakusz1github** [cloudflare/cloudflared#1156]
**Describe the bug**
not correctly starting

**To Reproduce**
1. Configure '...'
2. Run '....'
3. 
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        C:/teamcity-agent/temp/buildTmp/go/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x37f590 sp=0x37f570 pc=0x1084695
rax     0x0
rbx     0x2913ec0
rcx     0x2e95000
rdi     0x7fffffde000
rsi     0x37f790
rbp     0x37f6d0
rsp     0x37f568
r8      0x0
r9      0x37f7d0
r10     0x2965e58
r11     0x21
r12     0x37f7b0
r13     0x1
r14     0x2913260
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 
5. cloudflared config: standard

**Expected behavior**
Run and connect to cloudflare

**Environment and versions**
 - OS: Windows 7
 - Architecture: intel x64
 - Version: 2024.1.2

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by jcsf** [comment]
Hi,
Go 1.21 no longer supports Windows 7, more info [here](https://github.com/golang/go/issues/57003), since cloudflared is now compiled with go 1.21, it will not work on Windows 7. Note that Windows 7 is no longer supported by Microsoft since 2020 https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962. Therefore, the only way for you to have it working again is by upgrading your operating system.
