### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by bezi18** [cloudflare/cloudflared#1184]
Hello
How can I update the installed version of the tunnel?

**Comment by sevensolutions** [comment]
How did you install it? Depends on the installation method.

**Comment by bezi18** [comment]
mkdir Argo && cd Argo

wget https://github.com/cloudflare/cloudflared/releases/download/2023.10.0/cloudflared-linux-amd64 && chmod +x cloudflared-linux-amd64

./cloudflared-linux-amd64 tunnel login

./cloudflared-linux-amd64 tunnel create argo01

./cloudflared-linux-amd64 tunnel route dns argo01 your.subdomain.com

tmux

./cloudflared-linux-amd64 tunnel --url localhost:?? run argo01

**Comment by sevensolutions** [comment]
Then you just need to download the new version in the same way.
I think it's also possible to to a rolling update and start the new one in addition and then stop the old one, but i've never tried that.

**Comment by jcsf** [comment]
Yes, you can roll upgrade because cloudflared supports multiple replicas of the same tunnel, you just need to use the same token across all replicas. Regarding the way to upgrade, is what @sevensolutions said, since you didn't install it with any package manager, just download the most recent version and use the binary.
