### ISSUE TITLE
proxy-dns with own local DNS server inside company network as fallback

### ISSUE THREAD

**Issue by dhlavaty** [cloudflare/cloudflared#122]
DNS-over-HTTPS (a.k.a. proxy-dns) documentation is very intricate so I'm not sure if this is even possible.

I run `cloudflared proxy-dns` in docker on my local machine, and have set DNS to point to 127.0.0.1. And it works flawlessly.

But...we in our company, we also have some internal domains (like `server.location.companyname.net`. Those are resolved only by our local DNS server, that is accessible only witin internal network.

I can insert some of them into my own `hosts` file, but that is not very convenient obviously.

How can I setup `cloudflared proxy-dns` to also use our local DNS server as "a-last-place-to-look-for-a-domain" ?

**Comment by stephenjamieson** [comment]
I personally use a local dnsmasq server (listening on localhost) that forwards internal domains to the internal DNS and everything else to cloudflared.  This question is probably better answered in the forums than a bug/issue.

**Comment by abelinkinbio** [comment]
Hi there - Abe, new Tunnel PM here 👋 We've released quite a few exciting developments since this issue was reported. Have you tried building our private network feature? 

- https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel

If you're looking for Private DNS support in your internal network we may have some cool news for you soon 👀
