### ISSUE TITLE
Recursive DNS Lookups

### ISSUE THREAD

**Issue by clontarfx** [cloudflare/cloudflared#135]
Performing an Open Resolver test against my cloudflared DNS over HTTPS instance shows it has recursive lookups enabled. I have had a quick look through any associated documentation and cannot find a toggle or option to disable this.

Recursive DNS lookups are an integrity no-no, so I would like to be able to ensure my DNS server does not get used as a DDoS launchpad.

How does one disable the recursive lookup functionality in cloudflared?

**Comment by Tugzrida** [comment]
Forgive me if I'm misunderstanding, but in DoH itself there's not really such a thing as recursive lookups. cloudflared (a DoH stub resolver) uses DoH to securely query upstream recursive/caching DNS servers - essentially bringing a secure endpoint of whatever upstream you choose to your local machine(on `localhost` by default).

These upstream servers(such as 1.1.1.1, 8.8.8.8, etc.) must recursively query the DNS as they aren't authoritative for anything themselves, and would not be able to return any answers otherwise.

Usually the term 'open resolver' refers to authoritative DNS servers who will recursively look up domains they aren't authoritative for or private company/ISP resolvers that are accessible from outside that company/ISP. 1.1.1.1, 8.8.8.8, etc. are open resolvers on purpose, as ISP-independent resolvers.

If you do happen to be implementing cloudflared on your own resolver server with a public IP, you will want to implement firewall rules to lock down where DNS queries can come from.

**Comment by clontarfx** [comment]
Thanks for the reply. Basically I am just parroting security concerns
forwarded to me by my hosting provider. I am not sure if their issue is
that anyone can query my DNS server, or that it performs recursive lookups.

As you say, it would be necessary for "my" resolver to return recursively
as it is forwarding to 1.1.1.1.

I was using my understanding of other resolvers like bind9 that have an
option to not perform recursive lookups in its configuration.

**Comment by Tugzrida** [comment]
Your hosting provider is most likely concerned that it’s accessible to anyone. There are a few initiatives that search for open resolvers and then report them to their respective network admins because as you mentioned, they can be used for DDOS attacks. In your case, cloudflared is essentially making your server an extension of 1.1.1.1(or whatever upstream you’ve set).

The recursive options in other programs like bind9 control the built-in recursion. With it on, bind itself would directly query the root of the DNS, TLDs, and everything else down the line. With it off bind will just return answers for zones it’s authoritative for, or additional resolvers such as 1.1.1.1 can be set as an upstream recursor.

For your case:
- If you only need access from the machine cloudflared is running on, set it to listen on the loopback address rather than a public address
- If you have static IP ranges/addresses you use the server from, use a firewall such as ufw to restrict access to those ranges/addresses.
- Move cloudflared inside the network where it’s being used, behind that firewall.

However, if you have this server on a hosting provider and are using it remotely to use DoH, that does defeat the purpose of DoH, as connection from the end device to your server will be unencrypted.

**Comment by clontarfx** [comment]
Thanks for the additional information. Obviously now it makes sense, as you've described the use case properly. I've now since set up cloudflared on my internal network to tunnel to 1.1.1.1, and configured cloudflared on my public host to do the same (and perform it's lookups locally).

I suppose I was hurriedly trying to setup a central DNS Forwarder/Tunnel without understanding all of the moving parts. Perhaps my original use case is better intended for a VPN'd network.

Thanks!

**Comment by Tugzrida** [comment]
Glad I could be of help! Yes, a VPN could make your original case make sense, however it may introduce some latency, depending on how far away your server is.
