### ISSUE TITLE
cloudflared with internal Docker Registry

### ISSUE THREAD

**Issue by forestoden** [cloudflare/cloudflared#165]
Is it possible to use cloudflared/Cloudflare Access to protect a Docker Registry and be able to access it via native `docker` commands (`login`/`push`/`pull`/etc)?

It seems like we'd need to add a custom header into Docker and then rebuild `docker` for all of our developers to automatically inject this header into the requests. This doesn't seem like an approach we'd want to take and might not be stable.

I see `cloudflared` has a `curl` built in that could be used to manually curl requests to and from the Docker Registry. The Cloudflare Access documentation also states

> It is possible also to use the `put` command with `cloudflared` for any Unix tool to include the token in the request.

But there are no examples and I'm not quite sure what this is trying to say.

Any suggestions would be appreciated!

**Comment by daltoniam** [comment]
I might consider trying out the SOCKS5 proxy in cloudflared to protect the docker registry. Right now it is tested to work for Kubernetes, but it is a generic SOCK5 proxy so it might work for docker as it appears to support SOCK5.

https://docs.docker.com/network/proxy/

Cloudflare K8 documentation for reference:
https://developers.cloudflare.com/access/other-protocols/kubectl/

A rough example (untested): 

The setup should be similar to the kubernetes setup with the cloudflared on the origin side running hosting the docker registry:

```bash
# replace 127.0.0.1:5000 with whatever the port/local address of the docker registry (this example assume cloudflared is running on the same server).
cloudflared tunnel --hostname registy.site.com --url tcp://127.0.0.1:5000 --socks5=true
```

On the client/end user device make sure a cloudflared access forwarder is running:
```bash
cloudflared access tcp --hostname registy.site.com --url 127.0.0.1:1234
```

Then on the docker client edit the `~/.docker/config.json` with something like:
```json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "socks5://127.0.0.1:1234",
     "httpsProxy": "socks5://127.0.0.1:1234",
     "noProxy": "*.test.example.com,.example2.com"
   }
 }
}
```

**Comment by TownLake** [comment]
@forestoden we're going to go ahead and close this out after it's been 6 weeks, but please feel free to reopen.

**Comment by dem972** [comment]
Hi @daltoniam,

I'm facing the same issue and I followed your instruction. On my config I set 
```
ingress:
  - hostname: host.domain.com
     service: tcp://mygitlab.domain.com:1234
     originRequest:
           proxyType: socks
```
On my docker config I add :

` "proxies" : {
    "default" : {
      "httpsProxy" : "socks5://127.0.0.1:1234",
      "httpProxy" : "socks5://127.0.0.1:1234",
      "noProxy" : "hub.docker.com"
    }
  }`

I still have an error **Error response from daemon: error unmarshalling content: invalid character '<' looking for beginning of value**

I don't know if someone can help me with that. 

Many thanks

**Comment by rkerno** [comment]
Hi @dem972, I think this error regarding the invalid character might be due to requests that docker makes for metadata via the gitlab URL.  I reached this conclusion after testing registry access without cloudflare - it still wouldn't work whilst I had cloudflare teams configured for the gitlab URL.

**Comment by shubb30** [comment]
@dem972, Are you using Cloudflare Teams?

We are trying to access a Gitlab registry that is behind Cloudflare Teams, and I get the same unmarshalling error that you get.  I believe the `<` character it is complaining about is because the request is getting redirected to the Teams authorization page.

`
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"robots\" content=\"noindex\">\n    <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width\">\n    <title>Cloudflare Access Error</title>\n\n    <style>
`

**Comment by binaryfire** [comment]
@shubb30 Did you figure out fix for this? I'm having the same problem at the moment. What's odd is that it's happening even when I add a Bypass policy for the IPs I'm trying to log in from.
