### ISSUE TITLE
Documentation for tunnel caching

### ISSUE THREAD

**Issue by sdn90** [cloudflare/cloudflared#186]
I'm a new Argo Tunnel user and it took me a while to figure out that Cloudflare was caching my static assets due to the rules set on my domain.

My use case is exposing a local dev server. I was just under the assumption that nothing would be cached since that is that is how other tunnel services geared towards development (e.g. ngrok) work.

I think adding a note about this in the docs would be pretty helpful.

**Comment by TownLake** [comment]
Thanks for the feedback; we've [added a note](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/dns#optional-configure-additional-cloudflare-settings) that calls out how DNS and LB routing will use Cloudflare's reverse proxy settings and how those can be changed.

**Comment by hrdwdmrbl** [comment]
@TownLake Could you please update the note or your link to the note? I am not able to find out how to configure the caching. I resorted to enabled "development" mode on my whole application

**Comment by 1j01** [comment]
I agree this deserves further clarity, since caching is a footgun when it comes to development.
Here's how to configure it:

[Create a cache rule in the dashboard](https://developers.cloudflare.com/cache/how-to/cache-rules/create-dashboard/) for the hostname of your tunnel, which may be a domain or subdomain, so the Expression Preview looks like e.g. `(http.host eq "tunnel.example.com")`, and set the Cache Status to "Bypass cache", then click Deploy.

**Comment by EastSun5566** [comment]
I also recommend purging the cache manually. It’s much quicker. Go to <YOUR_DOMAIN> -> `Caching` -> `Configuration` -> `Purge Cache / Custom Purge` -> `Hostname`, then type your binding host and purge.
