### ISSUE TITLE
Healthchecks don't consider tunnel status

### ISSUE THREAD

**Issue by james-callahan** [cloudflare/cloudflared#188]
I saw in https://github.com/cloudflare/cloudflared/commit/c5af83af661c7b2bb971b271c1a76ea9f20c5371 that a /healthcheck endpoint was added to the metrics server.
However, it doesn't seem to take into account tunnel status: it returns OK even when the tunnel is not up.

Could you add a healthcheck endpoint that takes into consideration if the tunnel is actually up?

It should be a in a form suitable for a [kubernetes health check](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes).

**Comment by HofmannZ** [comment]
Any update on this?

**Comment by adamchalmers** [comment]
Hi all! We added a new healthcheck endpoint under /ready which is smarter. It will respond with HTTP 200 if cloudflared has at least one connection to the edge. It was added in https://github.com/cloudflare/cloudflared/commit/38fb0b28b6ff9ec662a3b262bae8d7d343022365 and it's designed for use with k8s. Please let me know if you have any other ideas around this!

**Comment by HofmannZ** [comment]
@adamchalmers any chance you could give a quick example?

**Comment by adamchalmers** [comment]
Start cloudflared with flag `--metrics localhost:3333` and then curl `localhost:3333/ready` to see.

**Comment by mijndert** [comment]
@adamchalmers sorry for replying to an old thread, I don't think my question warrants a new issue.

We're running cloudflared in AWS Fargate which does give me the option to of course set an entrypoint script, etc. But since curl is not included in the Dockerfile, I can't seem to figure out how to properly set up a Docker healthcheck.

Is my only option here to build my own Docker image that does include curl so I can reach the /ready endpoint and get a Docker healthcheck going?

Thanks.

**Comment by milindpatel63** [comment]
i can't seem to be able to setup a healthcheck

/bin/bash and /bin/sh not available inside docker container.

Any help?
