### ISSUE TITLE
missing config parameter in documentation

### ISSUE THREAD

**Issue by BrixSat** [cloudflare/cloudflared#195]
There is a missing config parameter here:

https://developers.cloudflare.com/argo-tunnel/reference/arguments/

The id parameter is very useful to identify tunnels origin server, and it is the only config not visible in the documentation. I had to view the code to find it out.

Thanks in advance, i just lost 1 day of work around this  :+1: 
Example config.yml

id: server_name_1
hostname: myspecialdomain.com
url: http://127.0.0.1:81
lb-pool: mypoolname
logfile: /var/log/cloudflare/argotunel.log
loglevel: info
proto-loglevel: info
pidfile: /var/run/cloudflared.pid
tag:
  - Name=not_used_or_not_visible_anywhere
  - id=not_used_or_not_visible_anywhere

**Comment by TownLake** [comment]
Thanks for the feedback and sorry for the delay (and rough edges there) on our side.

Since this ticket was opened, we have [released a new architecture for Argo Tunnel](https://blog.cloudflare.com/argo-tunnels-that-live-forever/) that includes [assigning a given Tunnel a name](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/create-tunnel) that is [referenced in the configuration file](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config#default-behavior) and can represent any value like server name - it does not need to map to a hostname used. The names [can also be listed](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/create-tunnel#list-available-tunnels) from `cloudflared` and the model adds stability to Argo Tunnel deployments.

We have also updated the configuration guide to include published documentation for [tag](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config#tag) that can be used to add additional context.
