### ISSUE TITLE
the last release doesn't include cloudflared-linux-amd64 

### ISSUE THREAD

**Issue by gitpel** [cloudflare/cloudflared#304]
the last release doesn't include cloudflared-linux-amd64 (2021.2.0)

**Comment by nmldiegues** [comment]
Hello @gitpel ,

We have noticed that as well. Thank you for reporting this.
2021.2.0 did change the Linux x86_64 build process and it seems like something got broke, so we'll investigate it right away.

In the meantime, feel free to continue using 2021.1.5 since there were no critical bug fixes nor new features added after it.

**Comment by nmldiegues** [comment]
This should now be fixed with 2021.2.1

Thank you for reporting the matter
