### ISSUE TITLE
MySQL Over Argo Tunnel

### ISSUE THREAD

**Issue by RhinosF1** [cloudflare/cloudflared#329]
I would like to proxy all our traffic over cloudflare.

I tried
>  sudo /usr/local/bin/cloudflared tunnel --hostname <domain> --origincert /path/to/.cloudflared/cert.pem --url mysql://localhost:3306

but that gave:

> Error validating origin URL: Currently Argo Tunnel does not support mysql protocol.

How can I proxy MySQL traffic?

**Comment by TownLake** [comment]
Hi @RhinosF1 - [we've released a new feature](https://developers.cloudflare.com/cloudflare-one/tutorials) that should make this use case (and others like it) possible for you - would you be interested in trying it out?

We need to update error messaging too.

**Comment by RhinosF1** [comment]
> Hi @RhinosF1 - [we've released a new feature](https://developers.cloudflare.com/cloudflare-one/tutorials) that should make this use case (and others like it) possible for you - would you be interested in trying it out?
> 
> We need to update error messaging too.

I'd be very interested.

**Comment by RhinosF1** [comment]
I'm not seeing anything about MySQL on that link. Could you advise?

**Comment by TownLake** [comment]
My fault - [this (more specific) link](https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel). You don't need to specify MySQL (or other protocols) in this new setup. The deployment provides a way to run what is essentially a private network on Cloudflare's network, which should handle this use case and others without trouble, but feedback very welcome.

**Comment by RhinosF1** [comment]
> My fault - [this (more specific) link](https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel). You don't need to specify MySQL (or other protocols) in this new setup. The deployment provides a way to run what is essentially a private network on Cloudflare's network, which should handle this use case and others without trouble, but feedback very welcome.

Is there any reason:

> sudo /usr/local/bin/cloudflared tunnel --hostname --origincert /path/to/.cloudflared/cert.pem --url localhost:3306

doesn't work.

**Comment by TownLake** [comment]
That command will create an HTTP connection to Cloudflare's edge and is primarily for connecting origin servers with a hostname that uses Cloudflare's DNS.

We've [historically used that structure](https://developers.cloudflare.com/cloudflare-one/applications/non-HTTP/ssh/ssh-connections) for non-HTTP use cases, like SSH, which your example follows - and users would run a corresponding instance of `cloudflared` on the client-side. However, that mode has limitations and is not as flexible as we wanted to support things like MySQL.

The new setup that creates this private network and has the flexibility for use cases like these is [this one](https://developers.cloudflare.com/cloudflare-one/applications/non-HTTP/ssh/ssh-connections) and, instead of `cloudflared` on the client-side you'll run Cloudflare's WARP agent.
