### ISSUE TITLE
Problem with websockets

### ISSUE THREAD

**Issue by msnelling** [cloudflare/cloudflared#40]
I have a problem using websockets with Argo.

Our application has three components
- IIS7 hosting the static content (*.html, *.js, *.png, …) over HTTP (currently from my workstation) on port 8003.
- Standalone application serving RESTful content over HTTP from `host2` on port 1341.
- Another standalone application serving streaming content over a websocket from `host1` on port 7171.

As per suggestions on the forums I proxy these URLs through Nginx with the below config to provide access through a single port and altered the server JS to use the new URL scheme.
```
server {
    listen       80;
    server_name  localhost;

    location /ws/ {
        proxy_pass http://host1:7171;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
    location /accountant/ {
        proxy_pass http://host2:1341/;
        proxy_http_version 1.1;
    }
    location / {
        proxy_pass http://localhsot:8003;
        proxy_http_version 1.1;
    }
}
```

IIS7, Nginx and `cloudflared` are both running on my workstation for testing.

I'm seeing the browser successfully request the static and RESTfull content from the correctly rewritten external URLs, however the websocket is not being rewritten at all and is attempting to connect to ws://localhost/ws/

I would have expected the ws:// URL to be rewritten to ws(s)://my.tunnel.url/ws/

What am I doing wrong? According to the Argo docs, websockets are "fully supported".

**Comment by acmacalister** [comment]
Your nginx configuration looks correct. Do you have logs on your WebSocket server showing any attempted connections? Which WebSocket server are you running? Many WebSocket servers have origin protection that will prevent cross forgery request.

**Comment by msnelling** [comment]
There are no websocket connection requests logged, this is most likely because the JavaScript on the browser is attempting to connect to ws://localhost (ie the machine the browser runs on rather than the actual server).

**Comment by acmacalister** [comment]
What errors do you receive in the network panel on the JS side? I was able to successfully set this up on my environment using a similar version of your nginx configuration. The only issue I ran into was origin protection I mention with trying to connect to different origin. Since nginx is a reverse proxy, I don't think the browser is going to try and connect to the upstream, since it doesn't know anything about it. On standard HTTP request, nginx is going to rewrite the request to the upstream and response with a 301 to send the client to that location to fetch the static assets from there. Generally most WebSocket client (like JS API in the browser), don't follow redirect, so you aren't going to see a rewritten request come through and rather you should see something about 101 switching protocols. 

Since I was able to get this working, I would check this:
1. The network panel & console in Chrome to see what errors you are getting. In my case, my JS connection is going to `wss:/<myzone>.com/ws/`. 
2. My Argo Tunnel is set to `cloudflared --hostname myzone.com http://localhost`. I check the logs/stderr that was returning a 502 at first with bad handshake because of the origin protection issue.
3. Check the nginx logs to make sure it is mapping to the WS server. You might also want to verify the trailing slash, as that can be a gotcha as well.

**Comment by analytically** [comment]
We're also seeing this, with JupyterHub as backend service.

```
time="2019-11-29T00:38:24Z" level=error msg="HTTP request error" error="websocket: bad handshake"
time="2019-11-29T00:38:41Z" level=error msg="HTTP request error" error="websocket: bad handshake"
time="2019-11-29T00:39:58Z" level=error msg="HTTP request error" error="unexpected EOF"
time="2019-11-29T00:41:03Z" level=error msg="HTTP request error" error="websocket: bad handshake"
```

**Comment by leo-mlq** [comment]
were you able to resolve it? Thanks
