### ISSUE TITLE
Sending https over `unix-socket`

### ISSUE THREAD

**Issue by jbergstroem** [cloudflare/cloudflared#402]
While configuring a `unix-socket` (currently using 2021.06.0), there seems to be no way for me to provide that I want to talk https, forcing me to stay with either TCP or skipping last mile encryption. It would be great if there was a url.scheme setting to handle this.

**Comment by nmldiegues** [comment]
Hello @jbergstroem ,

From my understanding, that's always been the case, right?  Just trying to double check since you mention `2021.6.0` release, but AFAIK this limitation always existed.

In any case, I agree, that should be possible.

**Comment by jbergstroem** [comment]
> From my understanding, that's always been the case, right? Just trying to double check since you mention 2021.6.0 release, but AFAIK this limitation always existed.

As far as I know, yep. As I re-read my comment I can see how it would seem misleading - sorry about that.

**Comment by danishprakash** [comment]
@nmldiegues would this be a task that a new contributor to this project can pick up?

**Comment by nmldiegues** [comment]
> @nmldiegues would this be a task that a new contributor to this project can pick up?

I would say that https://github.com/cloudflare/cloudflared/issues/406#issuecomment-873525251 is an easier one to start with if you wish to.

As for this one, it's not technically hard per se. But it would require extending the syntax of ingress rules to support this feature, since right now the unix socket is identified by the URL's scheme.

@adamchalmers  do you have a preference for how this could be done?

**Comment by nmldiegues** [comment]
This is the same as https://github.com/cloudflare/cloudflared/issues/502 which has a more comprehensive proposal/description. Closing this one in favour of that.
