### ISSUE TITLE
[Feature Request] Disabling Metrics Server

### ISSUE THREAD

**Issue by Rayqan** [cloudflare/cloudflared#415]
Would it be possible to add a way to disable the metrics server from starting at all? Apologies if this has already been added I looked everywhere and I could not seem to find any info on this.

**Comment by nmldiegues** [comment]
Hello @Rayqan ,

No, that is not possible.

What would be the reason to not want it running?

**Comment by Rayqan** [comment]
Any update on this @sudarshan-reddy?

**Comment by sudarshan-reddy** [comment]
Hey @Rayqan . Sorry about not reiterating what @nmldiegues said. This is closed because it is not possible to disable the metrics server. We rely on metrics for actual functions.

**Comment by victorstewart** [comment]
@sudarshan-reddy 

ended up here wanting to do the same thing. there wasn't any mention of the metrics server in the documentation on the ZeroTrust site, so i was surprised to find the tunnel fail to open because a metrics server wasn't listening.

what exactly is the point of the metrics server? as you say this is required for the tunnel to function?

**Comment by user8446** [comment]
I was looking for this as well.

As a workaround, I use `--metrics-update-freq 1440m` to update hourly instead of the default every 5 seconds which helps reduce resources used.
