### ISSUE TITLE
Filtering Ingress Traffic..

### ISSUE THREAD

**Issue by w3rkzeug** [cloudflare/cloudflared#506]
HI there,
Maybe i misunderstand the Cloudflare Tunnel docs...but'm facing several issues using the below config...
The tunnel works, the http/s rules work, but:
1. None of the ipRules work ...
2. The SSH one doesn't work tho... and ofc i have checked for other past issues but nothing helped to solve it...
I would highly appreciate an advice on how to solve/proceed from here using the cloudflare tunnel to route the public to the private cloud app....

![image](https://user-images.githubusercontent.com/40423351/141367676-7c3557d5-df15-4698-95e7-9db628e8276f.png)

**Comment by nmldiegues** [comment]
Hello @w3rkzeug ,

I suspect that you may be over-simplifying various steps involved in what you hope to achieve.
Rather than try to understand what you did, what may be missing, and explain those steps, I'll instead link full tutorials to each of the tasks you mentioned:
 - configuring a tunnel with ingress rules for HTTP and SSH: https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab
 - using the SSH browser client, rather than `cloudflared access ssh` (as per the tutorial above): https://developers.cloudflare.com/cloudflare-one/tutorials/ssh-browser
 - connect to private IPs behind a Tunnel, using the WARP client, without relying on `cloudflared access` at all: https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel

PS: the `ipRules` that you configured are only valid for an `ingress` rule with `service: socks-proxy`

**Comment by w3rkzeug** [comment]
Hi @nmldiegues ,
Thanks for the references, but my app that has to receive TCP traffic on several ports...and been testing that over & over again with new & clean tunnels , hello_world works for http, turning tcp://10.10.10.11:24000 & nothing happens... no logs...so here is a question..
Can i achieve that forwarding TCP traffic to specific ports using cloudflared & the CNAME pointing to the Tunnel ?
Thanks

**Comment by nmldiegues** [comment]
Arbitrary TCP proxying to origins can be achieved in 2 ways:
- with `cloudflared access tcp` on the client/requester side, as explained in the tutorials with various examples (see https://developers.cloudflare.com/cloudflare-one/tutorials/rdp and https://developers.cloudflare.com/cloudflare-one/tutorials/kubectl , besides the SSH example I already linked, which is essentially TCP too)
- or with a WARP Teams enrolled client, as explained in https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel

**Comment by w3rkzeug** [comment]
So if there is IoT that cannot be installed with cloudflared , then this is an issue..
Ok got it, 
Thank you.

**Comment by nmldiegues** [comment]
> So if there is IoT that cannot be installed with cloudflared , then this is an issue.. Ok got it, Thank you.

What I'd do in that case is configure the routing on such IoT devices to send all packets to some gateway server, where anything could be installed. This may or not be possible depending on what the set up is.
But ultimately you have to install something somewhere on the client side.
