### ISSUE TITLE
cloudflared tunnel --help doesn't list the --protocol option

### ISSUE THREAD

**Issue by jamielinux** [cloudflare/cloudflared#600]
**Describe the bug**
`cloudflared tunnel --help` doesn't list the `--protocol` option.

**To Reproduce**
1. `cloudflared tunnel --help`

**Expected behavior**
Show some information about the `--protocol` option.

**Environment and versions**
 - OS: Linux
 - Architecture: amd64
 - Version: 2022.03.1

**Comment by nmldiegues** [comment]
Hello @jamielinux ,
Thanks for reporting this.

This is on purpose, i.e., by design, since we envision that cloudflared should converge to a protocol over time.
Hence, users should not have a need to change this.

The reality is a bit more complicated, since we are still (slowly) rolling out `quic` transport for everyone --- but a lot of folks already opt-in for it explicitly to be able to use the latest features that come with it.

Still, we don't want to expose this flag on purpose, that's the key message.
