### ISSUE TITLE
Allow passing tunnel token via the file system.

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflared#645]
**Describe the feature you'd like**
I currently use named tunnels and run in docker containers. I would like to be able to use [docker secrets](https://docs.docker.com/engine/swarm/secrets/) with the containers. This is currently not possible because docker secrets are passed as a file and there is no way to read the file. It would be nice to be able to have `--secret-file` option, i.e. `cloudflared tunnel run --token --secret-file` or `cloudflared tunnel run --token </path/to/token/file>`.

**Describe alternatives you've considered**
Typically, you use `cat` in containers to read the files, but the rootless container does not have the cat executable so unable to use secrets that way

**Additional context**
Similar to #232. 

I would be happy to work on this if it is something that is worth implementing.

**Comment by nmldiegues** [comment]
You can see in:
```
→ cloudflared tunnel run --help | grep token
  --token value                                The Tunnel token. When provided along with credentials, this will take precedence. [$TUNNEL_TOKEN]
```

that it is also possible to pass the token as an environment variable. Those should be manageable as secrets in docker (compose, k8s, etc...) easily.

If you really want a file, then you can:
```
cloudflared tunnel token --cred-file /tmp/mysecret.json <TUNNEL>
```
And then you have `/tmp/mysecret.json` to put in your secret storage and to use.

All in all, I think there are enough ways to do this, and I would skip yet another way. Free free to open back and discuss further.

**Comment by nmldiegues** [comment]
> The purpose of docker secrets is to avoid putting secrets as environment variables.
> I admit that this is an edge case, but the goal is to be able to use remote managed tunnels via docker secrets.

But that's my whole point:  docker secrets can be injected into the container via both files as well as environment variables. The values still come from the secret storage. The way they are made available to the container is what differs.

**Comment by Cyb3r-Jak3** [comment]
How do you inject secrets as environment variables? From the documentation I have seen, it is only possible as a file

As an example, I have this compose file with a file called `token.secret` in the same directory that contains a remote tunnel token.
```yaml
version: "3.9"

secrets:
  cloudflare_token:
    file: "token.secret"

services:
  cloudflared:
    image: cloudflare/cloudflared:2022.5.1
    command: tunnel run
    secrets:
      - cloudflare_token
    environment:
      - TUNNEL_TOKEN=/run/secrets/cloudflare_token
```
Running `docker-compose up` gets
```
F:\git\cloudflare-secrets> docker-compose.exe up
[+] Running 1/1
 - Container cloudflare-secrets-cloudflared-1  Recreated                                                                                                                                                         1.4s 
Attaching to cloudflare-secrets-cloudflared-1
cloudflare-secrets-cloudflared-1  | Provided Tunnel token is not valid.
cloudflare-secrets-cloudflared-1  | See 'cloudflared tunnel run --help'.
cloudflare-secrets-cloudflared-1 exited with code 255
```

If I replace with 
```yaml
version: "3.9"

secrets:
  cloudflare_token:
    file: "token.secret"

services:
  cloudflared:
    image: cloudflare/cloudflared:2022.5.1
    command: tunnel run --token /run/secrets/cloudflare_token
    secrets:
      - cloudflare_token
```
I get the same output

**Comment by nmldiegues** [comment]
The problem is that you are setting the TUNNEL_TOKEN To the file path, not to the token itself.
The env var needs to have the actual string contents of the token.

Maybe you want to use something like https://builtin.com/software-engineering-perspectives/docker-compose-environment-variables instead?

**Comment by Cyb3r-Jak3** [comment]
>  The env var needs to have the actual string contents of the token.

The way that [docker secrets](https://docs.docker.com/engine/swarm/secrets/) work is that the secret info, in this case, the token, is passed to the container via a file.
> In terms of Docker Swarm services, a secret is a blob of data, such as a password, SSH private key, SSL certificate, or another piece of data that should not be transmitted over a network or stored unencrypted in a Dockerfile or in your application’s source code
> When you grant a newly-created or running service access to a secret, the decrypted secret is mounted into the container in an in-memory filesystem. The location of the mount point within the container defaults to /run/secrets/<secret_name>

Other images typically use an environment variable that ends in `_FILE` ie with mysql `MYSQL_ROOT_PASSWORD_FILE` instead of `MYSQL_ROOT_PASSWORD_FILE`

**Comment by beefstew809** [comment]
To reiterate, docker secrets allows us to have encrypted secrets at transit and at rest and makes it easier to keep tokens out of version control since it is not in the .env file. To the best of my (limited) knowledge, environment variables do not give us the same benefits of encryption at transit and rest. In my opinion, unless there is a more secure way to pass the token to a docker container, this should not be closed and should be worked on as a security enhancement.

**Comment by nmldiegues** [comment]
> In my opinion, unless there is a more secure way to pass the token to a docker container, this should not be closed and should be worked on as a security enhancement.

I want to reiterate on my comment in https://github.com/cloudflare/cloudflared/issues/645#issuecomment-1127393680 above, where I said:

> If you really want a file, then you can:
> 
> ```
> cloudflared tunnel token --cred-file /tmp/mysecret.json <TUNNEL>
> ```
> 
> And then you have `/tmp/mysecret.json` to put in your secret storage and to use

So there's a way to rely on a file, which is why I closed the issue, regardless of the discussion around the environment variables.

**Comment by Cyb3r-Jak3** [comment]
> If you really want a file, then you can:
> ```
> cloudflared tunnel token --cred-file /tmp/mysecret.json <TUNNEL>
> ```
> And then you have /tmp/mysecret.json to put in your secret storage and to use.

Doesn't this require having a `cert.pem` and a tunnel credentials file in the docker container?

With a docker-compose of
```yaml
version: "3.9"

secrets:
  tunnel_file:
    file: "tunnel_info"

services:
  cloudflared:
    image: cloudflare/cloudflared:2022.5.1
    command: tunnel token --cred-file /run/secrets/tunnel_file 8be772befd147a8df540aae0fa15c047
    secrets:
      - tunnel_file
    volumes:
      - ./cloudflared:/etc/cloudflared/:ro

```
With `./cloudflared` having a `config.yml`, `cert.pem` and tunnel credentials file. I can get it to work



Right now to get a connector online you run `docker run cloudflare/cloudflared:2022.5.1 tunnel --no-autoupdate run --token <token id>` where the token appears to be a base64 encoded JSON string that has a tunnel credential file information. The desired behavior is to be able to pass that same connector token is as a file.

**Comment by nmldiegues** [comment]
> Doesn't this require having a cert.pem and a tunnel credentials file in the docker container?

This would be done once per tunnel only, as part of your setup that would generate/handle/manage the secret so that it would be available in the future for your container to use.


> Right now to get a connector online you run docker run cloudflare/cloudflared:2022.5.1 tunnel --no-autoupdate run --token <token id> where the token appears to be a base64 encoded JSON string that has a tunnel credential file information. The desired behavior is to be able to pass that same connector token is as a file.

Let me make it extra clear:
 1. you create the Tunnel in the UI
 2. you run `cloudflared tunnel token --cred-file /some/path/tunnel.json <TUNNEL>`
 3. now you make /some/path/tunnel.json available to your container via whatever volume
 4. the container command should be: `tunnel --credentials-file /volume/path/tunnel.json run <TUNNEL>`

Steps 1/2 can be skipped if you create the Tunnel via the CLI and manage it that way.

No need for the `cert.pem`.

**Comment by Cyb3r-Jak3** [comment]
> This would be done once per tunnel only, as part of your setup that would generate/handle/manage the secret so that it would be available in the future for your container to use.

Ah, this is the step that I was missing. I was attempting to do it all in the container 😅. Thanks for staying with me on this

**Comment by etienne-napoleone** [comment]
Thanks for the explanation, got it working this way.
Would have been awesome to also just make it a little bit more convenient? at least at the docker image level ...

**Comment by sderungs** [comment]
Following the conversation above and specially @nmldiegues last answer I understood that cert.pem would only be required to generate the tunnel.json file but that after that it's not needed anymore and only tunnel.json needs to be mounted into the Docker container.

However, if I do so the container complains at startup about the missing cert.pem.

```
2023-02-19T22:46:27Z INF Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared] originCertPath=  
2023-02-19T22:46:27Z ERR You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/service/ for more information. originCertPath=
error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path
```

Apologies if this question might sound dumb - but why does it still ask for the cert.pem? Shouldn't the tunnel.json have all the credential information?

After all, if I would not run the service in a stack but just as a single container with `docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token someTokenHere` it would also not request that and also not generate an API token in my profile. I'm a bit at a loss here 😅

**Comment by ProfessorCha0s** [comment]
For anyone running into this later and a bit confused like I was, here is what you need to do (Replace \<TUNNEL\> with the name of your Tunnel as shown in the cloudflare dashboard)

1. From your system where docker is running (not the container) you will need cloudflared installed (instructions outside the scope of this conversation, but easy to find). Then you can pull your token and temporarily store as a json file by running
`cloudflared tunnel token --cred-file /some/path/tunneltoken.json <TUNNEL>`

2. Read that file into your docker secret
`docker secret create cloudflareTunnelToken /some/path/tunneltoken.json`

3. (Optional) Now that you have it saved as a secret you can delete the tunneltoken.json file if you want.

4. Finally you can use it in compose as in this example
```
version: '3.9'

secrets:
  cloudflareTunnelToken:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped    
    secrets:
      - cloudflareTunnelToken
    command: tunnel --credentials-file /run/secrets/cloudflareTunnelToken run <TUNNEL>
```

**Comment by josekommisar** [comment]
I will post my experience to encourage others not to worry about the process.
I previously tried many combinations with environments or secrets to the Cloudflared container with no success.
Many hours, I should point out.
I performed the steps gathered from this thread, and BANG is working.
To expand a little on the steps of @ProfessorCha0s:
1- I made a micro cloud VM running Ubuntu and installed Cloudflared binary via ssh session, per instructions on the Cloudflare Zero Trust homepage. You will need the name of your tunnel.
2- After installing Cloudflared, you must run 'cloudflared tunnel login' on the ssh session to generate a configuration file with your login details. The login is made via a URL you copy and run on your browser. The cert.pem file is the result output in the server. Otherwise, you cannot perform the next step.
3- After you have made login (and cert.pem generated), you can run the command 'cloudflared tunnel token --cred-file /some/path/tunneltoken.json <TUNNEL>'
4- And finally, as pointed out by @ProfessorCha0s, you can use or copy the JSON file to another server with docker swarm, create a secret, deploy the cloudflared container with his compose file, and have your tunnel working, without worrying about disclosing your token. 
I've done it that way to change the tunnel to another server with more resources, where I will run my apps.
I thank you all for the discussion and solution.

**Comment by catharsis71** [comment]
> For anyone running into this later and a bit confused like I was

I'm still confused because this doesn't work

```
# docker logs cloudflared
2023-08-31T22:12:06Z ERR Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable originCertPath=
error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path
2023-08-31T22:12:07Z ERR Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable originCertPath=
error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path
2023-08-31T22:12:08Z ERR Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable originCertPath=
error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path
2023-08-31T22:12:09Z ERR Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable originCertPath=
error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path
2023-08-31T22:12:10Z ERR Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable originCertPath=
error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path
```

**Comment by catharsis71** [comment]
> I will post my experience to encourage others not to worry about the process.

the Docker container still complains about lack of an origin certificate & will not run

how do you get the origin certificate into the container?

**Comment by josekommisar** [comment]
Did you generate the cert.perm file and the .JSON cred-file and pass the JSON to the container?
It was the only way it worked for me. 
I have no deep understanding of the method it exposes the string at run time. Why it works in the stack deploy on CLi ‘—-token <literal-string>’, and why it doesn’t with ‘--token $VAR-STRING’. The cloudflared image does not pass the variable/secret to the container at run time in a format it can work with, different implementation looks like. It expects a JSON format. 
The route discussed here was through first making a normal package/process/binary install and generation of the auth chain needed. In my case using a temporary machine/server to just obtain the JSON credentials.

**Comment by artbird309** [comment]
@catharsis71 I had the same issue but I figured out that it was a permissions issue for the secret file. I was not able to figure out what uid the cloudflared user was running so I change my permissions to 404 (read for owner and others) on the tunneltoken secret file and it worked fine without the cert.pem.

**Comment by j0sh** [comment]
Adding another vote for being able to read the token directly from a file, rather than going through the steps to get the cert, JSON, UUID, etc - doing so kind of defeats the purpose of the one-shot [remote setup process](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-remote-tunnel/).

For reference, it is a convention for Docker env vars to have a `_FILE` suffix specifically for this type of use case [1], eg

TUNNEL_TOKEN_FILE=/run/secret/cf_tunnel_token

would basically translate to something like:

TUNNEL_TOKEN=$(cat /run/secret/cf_tunnel_token)

although of course this is just a convention and this type of translation isn't built into Docker - it needs explicit application support, hence this issue.

[1] [Source](https://docs.docker.com/compose/use-secrets/) - very last note on the bottom of the page

<img width="555" alt="image" src="https://github.com/cloudflare/cloudflared/assets/292510/f05b39a5-a823-423b-ae77-4f897efad7f1">

**Comment by oluceps** [comment]
`EnvironmentFile` option could pass secrets to app with env vars.
```
; env
TEST=1
```

```
...
EnvironmentFile=/some/env
ExecStart="echo $TEST"
```

It outputs 1 in stdin.

**Comment by ZJohnAsZ** [comment]
Hi, I came across this discussion while trying to pass the token as a secret in my docker-compose file. Should I install and use docker swarm, just for this?

So far I went through the different steps to get the json file with the docker exec -it cloudflared way, so no need for vm or installing the cloudflared app directly OS.


1- Create a temporary folder in $DOCKERDIR  and give it chmod 777, as to not get permissions issues when generating the json file
2- Add a temporary volume to the compose file 
volumes: 
      - $DOCKERDIR/cf_token:/cf_token/
3- Start the cloudflared container
4- Generate the cert.pem at the container level
     `docker exec -it cloudflared cloudflared tunnel login`
     
3- Generate and save the json cred-file
    `docker exec -it cloudflared cloudflared tunnel token --cred-file /cf_token/cf_tunnel_token.json <TUNNEL_NAME>`
    
4- Not sure what to do from there install docker swarm to use it as a secret or load it from the json file with the `tunnel --credentials-file /volume/path/tunnel.json run <TUNNEL>` command.

I did not use docker swarm yet, would it change much `docker swarm init` on my local personal server and then create secrets with all my files, instead of having a secrets folder of files? Thank you to anyone willing to reply to me.

**Comment by j0sh** [comment]
> Hi, I came across this discussion while trying to pass the token as a secret in my docker-compose file. Should I install and use docker swarm, just for this?

@ZJohnAsZ Not to derail this topic but [this gist](https://gist.github.com/j0sh/b1971bfbbffeb92709cf096fb788f70c) shows my approach with Docker Compose. Basically invoke cloudflared in a shell (via multi-stage busybox build) and read the secrets file into a TUNNEL_TOKEN env var prior to execution.

**Comment by ZJohnAsZ** [comment]
> @ZJohnAsZ Not to derail this topic but [this gist](https://gist.github.com/j0sh/b1971bfbbffeb92709cf096fb788f70c) shows my approach with Docker Compose. Basically invoke cloudflared in a shell (via multi-stage busybox build) and read the secrets file into a TUNNEL_TOKEN env var prior to execution.
@j0sh Thank you for the reply. I am fairly new to docker/containers, I will explore the multi-stage way. New things to learn. :)

**Comment by ZJohnAsZ** [comment]
> @ZJohnAsZ Not to derail this topic but [this gist](https://gist.github.com/j0sh/b1971bfbbffeb92709cf096fb788f70c) shows my approach with Docker Compose. Basically invoke cloudflared in a shell (via multi-stage busybox build) and read the secrets file into a TUNNEL_TOKEN env var prior to execution.

@j0sh Thank you for the reply. I am fairly new to docker/containers, I will explore the multi-stage way. New things to learn. :)

**Comment by adam-stamand** [comment]
Thanks @j0sh for the workaround, it worked well for me. 

+1 to address this the right way with a `TUNNEL_TOKEN_FILE`; not sure of the author's hesitation there.

**Comment by bfg100k** [comment]
+1 for TUNNEL_TOKEN_FILE

**Comment by mbratchikov** [comment]
Using Google Secret Manager with Google Kubernetes Engine has [limitations](https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component#limitations) - secrets can be only read from file. It will be very nice to read tunnel_token from the file.
+1 for TUNNEL_TOKEN_FILE

**Comment by tetious** [comment]
I'm uncertain why there is so much push-back to making this more ergonomic by following the "standards" established by other docker containers. Is there something I'm missing that makes adding this painful or insecure?

The provided workarounds are serviceable, but all have drawbacks and are varying degrees of unfriendly to use.

Please reconsider making this nicer by implementing `TUNNEL_TOKEN_FILE`.

**Comment by DenisMir** [comment]
WTF 2024 an still no support for `TUNNEL_TOKEN_FILE`. This must be a joke. Wake up Cloudflare and follow the conventions!

**Comment by ehellman** [comment]
This should really be reopened. Cloudflare tunnels are widely used and not having `TUNNEL_TOKEN_FILE` available for docker secrets is a security concern. The current workarounds still make it more of a hassle to set up than it needs to be. I run maybe 60 services in my swarm, `cloudflared` is the **ONLY** one where I have to use 1Password Secrets directly for the token inside an .env file instead of using docker secrets like every other one supports.

**Comment by minhio** [comment]
hello, it is now 2025

**Comment by DenisMir** [comment]
Guys get this done please!

**Comment by MattRogish** [comment]
Agreed; I run Cloudflare managed tunnels and do not want the token visible in the `ps` list; plucking just the token from a file is necessary because it's cumbersome to do otherwise in a system service in e.g MacOS

**Comment by hobgoblina** [comment]
@nmldiegues can we get this reopened? docker secrets are a standard security feature that many users expect to be available for any well-maintained container. requiring users to come up with alternative methods for securing keys is bad practice. there's obviously a lot of people who want this, and it's not a big ask in terms of dev work.

**Comment by shopeonarope** [comment]
It's possible to convert the `TUNNEL_TOKEN` into a usable credential-file by decoding it and changing the field names:
```
echo -n <TUNNEL_TOKEN> | base64 -d | sed 's/"a"/"AccountTag"/;s/"t"/"TunnelID"/;s/"s"/"TunnelSecret"/' > cred-file.json
```
I prefer this because there's no need to run `cloudflared login` nor `cloudflared tunnel token`.

**Comment by jprinaldi** [comment]
Just circling back on this — is there any chance native support for Docker secrets might be reconsidered in the future?

It's a pretty standard practice in Docker deployments, and having to work around it feels a bit off given how common this pattern is.

Would love to hear if it's something on the radar or definitively out of scope. Appreciate all the hard work on `cloudflared`!

**Comment by vladshcherbin** [comment]
It's actually working as of [2025.4.0](https://github.com/cloudflare/cloudflared/releases/tag/2025.4.0)

Secret:

```bash
printf MY_TOKEN | docker secret create cloudflare_token -
```

Stack:

```yml
version: '3.8'

services:
  tunnel:
    image: cloudflare/cloudflared:2025.4.0
    command: tunnel run
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflare_token
    secrets:
      - cloudflare_token
    networks:
      - tunnel
    deploy:
      mode: global

secrets:
  cloudflare_token:
    external: true

networks:
  tunnel:
    driver: overlay
    attachable: true
```

Tested with Docker Swarm 🥳

**Comment by unleftie** [comment]
here's a simpler option but without swarm/docker secrets


**cloudflared.env** file:
```
TUNNEL_TOKEN=<your_token>
```

**compose.yml** file:
```
services:
  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - cloudflared.env
```

**Comment by arrowmaster** [comment]
> here's a simpler option

While you might look at the above compose files and think that your solution is simpler, some of those are for a bare bones implementation to prove the feature works. The usage of secret is for more advanced deployment options where the secrets are stored separate from the rest of the stack configuration. The secret storage can have additional protection to have separate access controls than the stack configuration. This type of setup can also allow for secrets to be managed externally and automatically rotated by another service.

**Comment by unleftie** [comment]
> > here's a simpler option
> 
> While you might look at the above compose files and think that your solution is simpler, some of those are for a bare bones implementation to prove the feature works. The usage of secret is for more advanced deployment options where the secrets are stored separate from the rest of the stack configuration. The secret storage can have additional protection to have separate access controls than the stack configuration. This type of setup can also allow for secrets to be managed externally and automatically rotated by another service.

agree, when i was going through the whole thread again, i overlooked the part about docker secrets
