### ISSUE TITLE
--overwrite-dns does not work when only using the subdomain instead of the full hostname

### ISSUE THREAD

**Issue by regnaio** [cloudflare/cloudflared#649]
**Describe the bug**
`--overwrite-dns` does not work when only using the subdomain instead of the full hostname

Error:
```bash
Failed to add route: code: 1003, reason: An A, AAAA or CNAME record already exists with that host.
```

Example:
```bash
# Assuming your website is example.com
# Assuming example.com's DNS is currently empty

cloudflared tunnel create mytunnel

cloudflared tunnel route dns --overwrite-dns mytunnel mytunnel
# successfully creates a CNAME record for mytunnel.example.com

cloudflared tunnel delete mytunnel
cloudflared tunnel create mytunnel

cloudflared tunnel route dns --overwrite-dns mytunnel mytunnel
# fails with the error above: Failed to add route: code: 1003, reason: An A, AAAA or CNAME record already exists with that host.

cloudflared tunnel route dns --overwrite-dns mytunnel mytunnel.example.com
# succeeds, but the website needs to be included
```

`cloudflared tunnel login` requires that we choose a website, e.g. example.com. So, if we have 2 websites, we'll have 2 different `TUNNEL_ORIGIN_CERT`'s. Thus, including the website in `cloudflared tunnel route dns` (which is repetitive and prone to human error) should be optional

**Comment by kissana37** [comment]
for iOS<https://aka.ms/o0ukef>
________________________________
จาก: regnaio ***@***.***>
ส่งแล้ว: วันศุกร์, พฤษภาคม 20, 2565 10:48 PM
ถึง: cloudflare/cloudflared
สำเนาถึง Subscribed
เรื่อง: [cloudflare/cloudflared] --overwrite-dns does not work when only using the subdomain instead of the full hostname (Issue #649)


Describe the bug
--overwrite-dns does not work when only using the subdomain instead of the full hostname

Error:

Failed to add route: code: 1003, reason: An A, AAAA or CNAME record already exists with that host.

Example:

# Assuming your website is example.com
# Assuming example.com's DNS is currently empty

cloudflared tunnel create mytunnel

cloudflared tunnel route dns --overwrite-dns mytunnel mytunnel
# successfully creates a CNAME record for mytunnel.example.com

cloudflared tunnel delete mytunnel
cloudflared tunnel create mytunnel

cloudflared tunnel route dns --overwrite-dns mytunnel mytunnel
# fails with the error above: Failed to add route: code: 1003, reason: An A, AAAA or CNAME record already exists with that host.

cloudflared tunnel route dns --overwrite-dns mytunnel mytunnel.example.com
# succeeds, but the website needs to be included

Since cloudflared tunnel login requires that we choose a website, e.g. example.com, this behavior doesn't seem to make sense

**Comment by sudarshan-reddy** [comment]
This is very intentional for the specific reason you said. `human error`. It's easier to err on human error on the side of the user being explicit versus wildcards.

**Comment by nishan8500** [comment]
https://www.22winbd.com/index
