### ISSUE TITLE
Updates on Windows with `cloudflared.exe update` does not restart the service 🐛

### ISSUE THREAD

**Issue by arouene** [cloudflare/cloudflared#668]
**Describe the bug**
Cloudflared is updated with `cloudflared.exe update` on Windows, the service is not restarted

**To Reproduce**
1. Start the service
2. Run 'cloudflared.exe update' to update the service
3. Check if service is running (sometime it's not running)

![Screenshot from 2022-06-16 15-25-10](https://user-images.githubusercontent.com/20049990/174089450-f7dc8f2f-6a22-41a8-ab70-772094108ea0.png)

**Expected behavior**
Service is updated and running

**Environment and versions**
 - OS: Windows 2019 Standard edition (1809)
 - Architecture: Intel x86_64
 - Version: 2022.5.3 (built 2022-05-30-1513 UTC) from github

**Logs and errors**
No errors

**Comment by sudarshan-reddy** [comment]
Thanks for raising this! Let’s track it here: https://github.com/cloudflare/cloudflared/issues/695

**Comment by bshavermfin** [comment]
This appears to be a separate issue from #667 - is it expected behavior that the service will be stopped after running "cloudflared update"?  This is still happening as of today August 7th, 2024, updating from version 2004.6.1 to 2024.8.2.  Update completes successfully, but service is stopped after the update.
