### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by samasc30** [cloudflare/cloudflared#69]
Hi,
we are planning to expose multiple internal/legacy systems using Argo Tunnel and some of them are using WebDAV.
Seems like some methods work fine, for example: COPY, LOCK, UNLOCK
But some do not, for example: MKCOL

Is there a plan to support WebDAV?

**Comment by sssilver** [comment]
Hi,

Supporting WebDAV is currently not on the roadmap. HOWEVER, the reason WebDAV doesn't "just work" is probably due to some HTTP verb validation within the Golang HTTP implementation.

If anyone wants to take a look at what's happening with that and open a PR, we'd be thrilled to review it and get it merged.

**Comment by gsquire** [comment]
Could you add a `http.Handler` from [this package](https://godoc.org/golang.org/x/net/webdav)?

**Comment by samasc30** [comment]
Tested today and WebDAV related errors are still present.
Are there any news or plans for this issue?

**Comment by wpuckering** [comment]
I'm running into issues trying to access a service behind Argo Tunnel using WebDAV as well, seems like there's been no update on this for quite some time now?

**Comment by robertoandrade** [comment]
Running into the same exact issue here and was scratching my head trying to read the whole WebDAV spec to figure out what my client was doing wrong or my server was enforcing... to only learn after a few minutes searching that the CloudFlare tunnel is the one to blame! Any news on this guys?

**Comment by robertoandrade** [comment]
After trying to trace the requests made by the `cloudflared` tunnel client to my server vs the direct requests I was making to it, ie: via `curl` I noticed `cloudflared` makes chunk-encoded requests by default and provides a `--no-chunked-encoding` argument to disable that behavior :\ I guess WebDAV servers in general don't support that from clients and although most clients already know that, the tunnel one doesn't.

At least there's a workaround for the issue!

**Comment by robertoandrade** [comment]
[The official docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress#disablechunkedencoding) mention that option is default as `false` meaning chunked encoding is always on and disabled only for certain scenarios, perhaps WSGI/WebDAV are a few to be documented, but just wanted to raise the question of that being enabled by default for both HTTP/1.1 and HTTP/2.0 requests since HTTP 2.0 apparently has other mechanisms to handle that.

**Comment by abelinkinbio** [comment]
We recently released a new feature that allows users to connect any service that relies on TCP-based protocols to Cloudflare's network. This should help alleviate some of the issues mentioned above to start. 

Check it out: https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel
