### ISSUE TITLE
Remendation about issue vulnerable🐛

### ISSUE THREAD

**Issue by imhunterand** [cloudflare/cloudflared#738]
**Describe the bug**
I have reported a security vulnerabilities as refferences https://hackerone.com/reports/1657485 but your program company is lie
I see at the your `programs-policy` the bounty will be sent for 10days, but in my reports now is 20 days ago.

What happend to your company, hellow team ? Im not a new researcher here.
Im Offensive OSCP/OSEP the proffesional bug bounty hunter / security research.

WHY YOU LIE TO ME ? WHY YOU CHEATING MY TIME.!

**Comment by imhunterand** [comment]
ALERT FOR YOUR COMPANY REPUTATIONS!

**Comment by ejcx** [comment]
Hi, I lead product security at Cloudflare. Im not sure why we didn't respond and Ill get to the bottom of that and I appreciate the callout. This isn't a security vulnerability though. The report you made was essentially a self xss and we aren't going to fix it. Additionally it isn't a server-side request forgery because the request is coming from the clientside.
