### ISSUE TITLE
Update check failed

### ISSUE THREAD

**Issue by bompus** [cloudflare/cloudflared#77]
OS: Ubuntu 18.04.2

I think what happened is that I had ran "cloudflared update" manually on the shell, because the (2) cloudflared systemd services I had running had not auto-updated yet.

I'm guessing that when it went to auto-updated, something got confused, OR maybe both services were trying to auto-update at the same time and stepped on top of each other. I'm not sure if it's normal to see this in the system logs or not, but I'm posting here if you want to see what might have happened.

I am **not** using --no-autoupdate as I'd prefer cloudflared to stay up to date automatically and gracefully update as I read in the docs.

```
Mar 12 04:27:34 localhost cloudflared[140063]: time="2019-03-12T04:27:34Z"
 level=error msg="update check failed" error="rename
 /usr/local/bin/.cloudflared.old /usr/local/bin/..cloudflared.old.old: no such file or directory"
```

**Comment by BojanZelic** [comment]
I'm consistently getting this error as well. I'm running 2 cloudflared services on the host. I think they're getting confused as the update is probably happening simultaneously on each service.

**Comment by abelinkinbio** [comment]
Last month, we released a new feature with should help address your concern with graceful restarts. The new release allows users to run the same Tunnel from multiple instances of `cloudflared`. With this, instead of restarting `cloudflared` with expected downtime, users can spin up a second `cloudflared` instance. 

Check it out: https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel

**Comment by bompus** [comment]
Thanks.. I've been using multiple instances since the feature release and it seems to work well. I haven't really gone through an upgrade yet though, but if it works as advertised, this feature should resolve the issue.
