### ISSUE TITLE
🐛 We have the issue with Local Domain Fallback on Android devices.

### ISSUE THREAD

**Issue by duydo-ct** [cloudflare/cloudflared#777]
**Describe the bug**
We are facing an issue when connecting to our internal website https://www.domain-internal.org.
For this website, we :
- Added domain name: *.domain-internal.org and its IP arrange into Split Tunnel in Include mode.
- Configured Local Domain Fallback for domain-internal.org and pointed to our internal DNS server.
This setup works fine with macOS, Windows, Linux, and IOS but failed with Android (almost of versions 11, and 12).

**To Reproduce**
On Android device: When I enable WARP with the status **Connected** 
![image](https://user-images.githubusercontent.com/108656040/195495281-8a95f0da-dde0-4460-95f3-bef28e75b40f.png)

I can access via IP Internal like Vault tool with IP same: `10.10.112.55:8200 `it Okay

I found that Android cannot resolve domain` *.domain-internal.org ` through Local Domain Fallback when WARP was connected.
![Screen Shot 2022-10-13 at 10 57 19](https://user-images.githubusercontent.com/108656040/195499349-48b007c6-b979-43fb-838d-c54366eb44ae.png)

**Expected behavior**

**Environment and versions**
 - Android OS: Redmi Note 11S
 - Android Version: 11
 - WARP Agent Version: 6.17 
 
 **Cloudflared version**
 -  Version: 2022.9.0

**Logs and errors**

**Additional context**

**Comment by bossmonkeyman** [comment]
@duydo-ct was this fixed in a specific release? I am experiencing this exact problem now on 2022.10.2

**Comment by duydo-ct** [comment]
@bossmonkeyman Not yet bro.

**Comment by abelinkinbio** [comment]
@duydo-ct this is the GitHub repository for the `cloudflared` client which is separate from the warp client. Unfortunately,  there is no warp client repository since that client is not open sourced, but I have forwarded this issue to the right team internally. Additionally, I'd recommend reaching to Cloudflare Support and sharing the ticket number here so that we can continue looking into this report and gather more details.
