### ISSUE TITLE
🐛 WebSocket connections don't work

### ISSUE THREAD

**Issue by francoataffarel** [cloudflare/cloudflared#863]
**Describe the bug**
Hello I'm trying using a script https://github.com/MEGALODON-SSH/MEGA/blob/30351fb6e4d99f400a955473925fc0ab4681285d/Modulos/wsproxy.py to send my ssh server via http/websocket over cloudflared.  But i cannot successfully send ssh ver via http/websocket.

This script will create a webserver http/websocket on port 80 sending all informations to ssh server. Then i use this command to create a tunnel
./cloudflared-linux-amd64 tunnel run --url http://127.0.0.1:80 -p auto tunnelname

But i'm cannot curl tunnelname.myserver.com in port 80 and receive ssh connection

**Comment by sudarshan-reddy** [comment]
Hey @francoataffarel ! I'd love to help you but this issue is lacking a lot of details for us to troubleshoot. 

Can you tell us how you set up the environmemt,
whats your ws server
whats the client
are you seeing any log messages?
What is the error you are seeing 

Feel free to open a new issue with this (the existing issue template is a good guideline for the details we need).
