### ISSUE TITLE
[*]🐛 Cloudflared Server Latest Version Bug

### ISSUE THREAD

**Issue by Yoxmo** [cloudflare/cloudflared#880]
Addition to users: alx-xlx bug report 
> commented [3 days ago](https://github.com/cloudflare/cloudflared/issues/878#issue-1548245391) 

I also have been getting this issue on `Macintosh OS 13.1 - 22C65`

brew is only updating to cloudflared version 2022.12.1 (built 2022-12-20-1251 UTC)

but tunnels had been working way after that version was released.

**Comment by Yoxmo** [comment]
After updating useing cloudflared update ( which didn't work until I uninstalled and restarted my computer) still receiving the error. Picture attached below.

<img width="971" alt="Screenshot 2023-01-21 at 5 12 32 PM" src="https://user-images.githubusercontent.com/94254616/213889005-b5a497c3-3c8d-4312-bd77-4b854a5a2caf.png">

**Comment by deanfourie1** [comment]
Same for me, im getting this on latest version on Debain 11 and 2022.12.1 on FreeBSD.
Neither of them work.

**Comment by sudarshan-reddy** [comment]
I’m looking into this. What config are y’all running cloudflared with?

**Comment by deanfourie1** [comment]
Im running on a stock Debain 11 VM (bullseye) and im trying to run on pfSense (FreeBSD).

Steps to products on a fresh debain install.

apt update
apt upgrade
apt install cloudflared
cloudflared tunnel login
cloudflare tunnel create <tunnel name>
cloudflare tunnel connect <tunnel name>

no go.

**Comment by sudarshan-reddy** [comment]
What is your cloudflare tunnel’s config? There’s usually a yaml if it’s locally managed or a remote config if it’s remotely managed.

**Comment by deanfourie1** [comment]
hmm cloudflared tunnel run works haha. fuck.

**Comment by deanfourie1** [comment]
sorry

**Comment by BennyTurtle** [comment]
I tried deleting a tunnel that was remotely managed and got this error which seems to be related as far as I can tell.
This is running the newest version from both apt and the standalone version on ubuntu server 22
`WRN Register tunnel error from server side error="Using Tunnels without a Cloudflare account now requires a more recent cloudflared version.\n\t\t\tPlease upgrade to the latest version available in order to use this feature by running: cloudflared update" connIndex=0 ip=
2023-01-24T11:36:52Z INF Retrying connection in up to 2s connIndex=0 ip=
2023-01-24T11:36:54Z INF Tunnel server stopped
2023-01-24T11:36:54Z ERR Initiating shutdown error="Using Tunnels without a Cloudflare account now requires a more recent cloudflared version.\n\t\t\tPlease upgrade to the latest version available in order to use this feature by running: cloudflared update"
2023-01-24T11:36:54Z ERR icmp router terminated error="context canceled"
2023-01-24T11:36:54Z INF Metrics server stopped
Using Tunnels without a Cloudflare account now requires a more recent cloudflared version.
                        Please upgrade to the latest version available in order to use this feature by running: cloudflared update`

**Comment by SilkePilon** [comment]
I'm also still getting this error

**Comment by ilyigna** [comment]
i am also getting this error

**Comment by Yoxmo** [comment]
> I’m looking into this. What config are y’all running cloudflared with?
 
The update worked for me, after doing `cloudflared tunnel update` but now I am getting a 403 Forbidden Error on my webpage I know everything is good on my end since i have made no changes to the hosting process so I don't know what is going on now?

**Comment by Yoxmo** [comment]
[!] Update: Everything works on my end. For those of you who are stilling have this issue it might be time to upgrade from legacy to named tunnel! 
 - If on mac stay away from brew and just upgrade via cloudflared and download from them directly.
 - Linux / try the same thing as well (avoid package manger and try cloudflared directly)
 - No idea if theres any issues on windows :/
