### ISSUE TITLE
🐛 `cloudflared tunnel route dns` can't create dns for a second tls

### ISSUE THREAD

**Issue by harryzcy** [cloudflare/cloudflared#905]
**Describe the bug**
`cloudflared tunnel route dns` converts `sub.domain2.com` to `sub.domain2.com.domain1.com`

**To Reproduce**
1. Create a tunnel in command line: `cloudflared tunnel create <tunnel>`
2. Create dns record for domain 1: `cloudflared tunnel route dns <tunnel> some-sub.domain1.com`
3. Create dns record for domain 2: `cloudflared tunnel route dns <tunnel> sub.domain2.com`
4. The output:
    ```
    2023-03-01T19:04:05Z INF Added CNAME sub.domain2.com.domain1.com which will route to this tunnel tunnelID=***
    ```

**Expected behavior**
DNS should be created for `sub.domain2.com` instead of for domain 1.

**Environment and versions**
 - OS: MacOS
 - Architecture: ARM64
 - Version: 2023.2.1

**Additional context**
Creating in UI works, so there's no problem with the tunnel, just the cli.

**Comment by obezuk** [comment]
Hi @harryzcy,

This is the expected behavior when cloudflared is using a `cert.pem` generated from `cloudflared login`. During the login process, this certificate is scoped to the selected domain. This is why you are observing the DNS record being nested within the parent domain name.

In order to use multiple domains I recommend generating another certificate for that `domain2.com` and serving it from another instance of cloudflared or switching to dashboard-managed Tunnels that support different domains from the same cloudflared instance.

**Comment by harryzcy** [comment]
Closing if it's expected
