### ISSUE TITLE
CLoudflare Windows 10 Pro RDP not working📝

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [cloudflare/cloudflared#927]
**Available Documentation**
[A link to the documentation that is available today and the areas which could be improved. ](https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/connections/connect-apps/use_cases/rdp.md#connect-to-rdp-server-with-cloudflared-access)

**Suggested Documentation**

- Confuse to select port number in both client and cloudflare tunnel configuration.
- Tunnel configuration port suggest to use port 3389 for RDP
- but, client command line argument dictate to use PORT other than 3389

Following guide didnt make sense
- localhost:3389 is not valid from where remote is taken, it will generate error

> While cloudflared access is running, connect from an RDP client such as Microsoft Remote Desktop:
Open Microsoft Remote Desktop and select Add a PC.
For PC name, enter localhost:3389.
For User account, enter your RDP server username and password.
Double-click the newly added PC.
When asked if you want to continue, select Continue.
When the client launches, a browser window will open and prompt the user to authenticate themselves. 

is there any demostration/documentation of of windows 10 is taken remotely from another windows 10 using cloudflare?

Any help will appriciated!

**Comment by mimicdotga** [comment]
Hi!
If I understand correctly, you are trying to set up rdp for windows 10. If you want to allow connection to your computer from an external network, you can use the cloudflare tunnel for this. On computer X where you have an rdp server running, you start cloudflared by pointing to the port on which the server is placed. On the other hand, on device Y from which you are trying to connect to device X, you must also have a cloudflare client, but in "access" mode - you enter the tunnel url and some local address, e.g. 127.0.0.1:12345 on which the cloudflare client will listen for connections. On the same device, you open the rdp client and enter the address 127.0.0.1:12345. It will be correct, because on this port the cloudflare client in access mode listens and forwards all data to the tunnel, which goes to the cloudflare client on computer X, which forwards them to the RDP server.
I hope I helped. Regards!

**Comment by OptifySudarshanPatil** [comment]
Hi @mimicdotga ,
Thanks for prompt replay.
i've setup tunnel as instructed here, [https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/connections/connect-apps/use_cases/rdp.md#connect-to-rdp-server-with-cloudflared-access](url) 
Whenever after running command on listening device "cloudflared access rdp --hostname rdp.example.com --url rdp://localhost:3388"
And after trying to connect from another PC with URL rdp.example.com (Mine is different url setup)
it prompt that RDP is not running.

Is there (someone tried and made) any video tutorial for making this work will be great?

**Comment by OptifySudarshanPatil** [comment]
Process in which i able to make RDP connection

1. Complete only this step on the system which need to be taken remote [Cloudflare RDP tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/use_cases/rdp/#1-connect-the-server-to-cloudflare-1)
2. This will setup Cloudflare tunnel and application with authantication policy. Leave this system.
3. Now open CMD on another system where remote need to be view and follow this steps [Connect User](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/use_cases/rdp/#2-connect-as-a-user)
4. Now RUN following command; "mstsc", it will open RDP window
5. Type Address "localhost:3389" or localhost:3388" whichwhere is available as per documentation, and press connect.
6. Now cloudflare application authantication page will popup, complete this process.
7. It will prompt for user id and password for Remote system.
8. Now you have connected via Cloudflare Tunnel!!!

It took me 3 days to figure out process correctly.
Kudos to cloudflare and thanks @mimicdotga
